name: Deploy Flaskex

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # Static Code Scan 
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }} .

      - name: List Images
        run: docker images

      # Image Scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Image to Registry
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}
          
  deploy:
    runs-on: ubuntu-latest
    
    needs: build

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup KUBECONFIG
        uses: vbem/kubeconfig4sa@v1
        with:
          server:     ${{ secrets.KUBEAPI_SERVER }}
          ca-base64:  ${{ secrets.K8S_CA_BASE64 }}
          token:      ${{ secrets.K8S_SA_TOKEN }}
          namespace:  myapp

      - name: Deploy Flaskex
        run: helm upgrade --install -f customvalues.yaml myapp .
